#pragma once

#include "rendertypes.h"

class Texture;

// =================================================================================================
// Platform-neutral OGL upload entry points used by base_noisetexture.
//
// Both functions do the full Deploy pipeline for an existing Texture object whose GL name has
// already been generated by Texture::Create(): they bind the texture, issue glTexImageNd with the
// per-format triple resolved via ToGLFormat(GfxPixelFormat), call tex.SetParams(false) (which the
// concrete subclass uses to set wrap/filter and — where appropriate — glGenerateMipmap), then
// release. On success tex.m_isDeployed is set to true.
//
// The functions are no-ops if the texture is already deployed.

bool Upload2DTexture(Texture& tex, int width, int height,
                     GfxPixelFormat fmt, const void* data) noexcept;

bool Upload3DTexture(Texture& tex, int width, int height, int depth, GfxPixelFormat fmt, const void* data, bool generateMips) noexcept;

// =================================================================================================
